### ISSUE TITLE
Live map is down

### ISSUE THREAD

**Issue by Niko9911** [olahepelto/bussikartta#2]
/busses are retuning empty array which causes no hsl bus in the map.

**Comment by olahepelto** [comment]
This is a reoccurring bug that has been plaguing the project for a while. Probable cause is that the mqtt connection to the hsl server is cut off in the python backend and not restored for some reason. Added a log to try to debug this issue.

**Comment by Niko9911** [comment]
Kaput

**Comment by olahepelto** [comment]
The apache2 virtualhost configuration has been broken for a while now. Fixed it.

**Comment by Niko9911** [comment]
@olahepelto If you need hosting for this, I can provide always some. As long it is non-profit.
